import gdxpds
import pandas as pd

# ---------- 1. 读取 GDX ----------
df = pd.read_csv('./CSV/Area_basin.csv')

# ---------- 2. 解析国家代码（取前三位） ----------
df["country3"] = df["region"].str[:3]

# ---------- 3. Mapping ----------
mapping = {
    "AFG": "XSA",
    "ALB": "XER",
    "DZA": "XNF",
    "ASM": "XSA",
    "AND": "XER",
    "AGO": "XAF",
    "ATG": "XLM",
    "ARG": "XLM",
    "ARM": "CIS",
    "ABW": "XLM",
    "AUS": "XOC",
    "AUT": "XE25",
    "AZE": "CIS",
    "BHS": "XLM",
    "BHR": "XME",
    "BGD": "XSA",
    "BRB": "XLM",
    "BLR": "CIS",
    "BEL": "XE25",
    "BLZ": "XLM",
    "BEN": "XAF",
    "BMU": "XLM",
    "BTN": "XSA",
    "BOL": "XLM",
    "BIH": "XER",
    "BWA": "XAF",
    "BRA": "BRA",
    "VGB": "XLM",
    "BRN": "XSA",
    "BGR": "XER",
    "BFA": "XAF",
    "BDI": "XAF",
    "CPV": "XAF",
    "KHM": "XSE",
    "CMR": "XAF",
    "CAN": "CAN",
    "CYM": "XLM",
    "CAF": "XAF",
    "TCD": "XAF",
    "CHL": "XLM",
    "CHN": "CHN",
    "COL": "XLM",
    "COM": "XAF",
    "COD": "XAF",
    "COG": "XAF",
    "CRI": "XLM",
    "CIV": "XAF",
    "HRV": "XER",
    "CUB": "XLM",
    "CYP": "XE25",
    "CZE": "XE25",
    "DNK": "XE25",
    "DJI": "XAF",
    "DMA": "XLM",
    "DOM": "XLM",
    "ECU": "XLM",
    "EGY": "XNF",
    "SLV": "XLM",
    "GNQ": "XAF",
    "ERI": "XAF",
    "EST": "XE25",
    "SWZ": "XAF",
    "ETH": "XAF",
    "FRO": "XER",
    "FJI": "XSA",
    "FIN": "XE25",
    "FRA": "XE25",
    "PYF": "XSA",
    "GAB": "XAF",
    "GMB": "XAF",
    "GEO": "CIS",
    "DEU": "XE25",
    "GHA": "XAF",
    "GIB": "XER",
    "GRC": "XE25",
    "GRL": "XLM",
    "GRD": "XLM",
    "GUM": "XSA",
    "GTM": "XLM",
    "GIN": "XAF",
    "GNB": "XAF",
    "GUY": "XLM",
    "HTI": "XLM",
    "HND": "XLM",
    "HKG": "CHN",
    "HUN": "XE25",
    "ISL": "XER",
    "IND": "IND",
    "IDN": "XSE",
    "IRN": "XME",
    "IRQ": "XME",
    "IRL": "XE25",
    "ISR": "XME",
    "ITA": "XE25",
    "JAM": "XLM",
    "JPN": "JPN",
    "JOR": "XME",
    "KAZ": "CIS",
    "KEN": "XAF",
    "KIR": "XSA",
    "PRK": "XSE",
    "KOR": "XSE",
    "KWT": "XME",
    "KGZ": "CIS",
    "LAO": "XSE",
    "LVA": "XE25",
    "LBN": "XME",
    "LSO": "XAF",
    "LBR": "XAF",
    "LBY": "XNF",
    "LIE": "XER",
    "LTU": "XE25",
    "LUX": "XE25",
    "MAC": "CHN",
    "MDG": "XAF",
    "MWI": "XAF",
    "MYS": "XSE",
    "MDV": "XSA",
    "MLI": "XAF",
    "MLT": "XE25",
    "MHL": "XSA",
    "MRT": "XAF",
    "MUS": "XAF",
    "MEX": "XLM",
    "FSM": "XSA",
    "MDA": "CIS",
    "MCO": "XER",
    "MNG": "XSE",
    "MNE": "XER",
    "MAR": "XNF",
    "MOZ": "XAF",
    "MMR": "XSE",
    "NAM": "XAF",
    "NRU": "XSA",
    "NPL": "XSA",
    "NLD": "XE25",
    "NCL": "XSA",
    "NZL": "XOC",
    "NIC": "XLM",
    "NER": "XAF",
    "NGA": "XAF",
    "MKD": "XER",
    "MNP": "XSA",
    "NOR": "XER",
    "OMN": "XME",
    "PAK": "XSA",
    "PLW": "XSA",
    "PAN": "XLM",
    "PNG": "XSA",
    "PRY": "XLM",
    "PER": "XLM",
    "PHL": "XSE",
    "POL": "XE25",
    "PRT": "XE25",
    "PRI": "XLM",
    "QAT": "XME",
    "ROU": "XER",
    "RUS": "CIS",
    "RWA": "XAF",
    "WSM": "XSA",
    "SMR": "XER",
    "STP": "XAF",
    "SAU": "XME",
    "SEN": "XAF",
    "SRB": "XER",
    "SYC": "XAF",
    "SLE": "XAF",
    "SGP": "XSE",
    "SVK": "XE25",
    "SVN": "XE25",
    "SLB": "XSA",
    "SOM": "XAF",
    "ZAF": "XAF",
    "SSD": "XAF",
    "ESP": "XE25",
    "LKA": "XSA",
    "KNA": "XLM",
    "LCA": "XLM",
    "VCT": "XLM",
    "SDN": "XAF",
    "SUR": "XLM",
    "SWE": "XE25",
    "CHE": "XER",
    "SYR": "XME",
    "TJK": "CIS",
    "TZA": "XAF",
    "THA": "XSE",
    "TLS": "XSE",
    "TGO": "XAF",
    "TON": "XSA",
    "TTO": "XLM",
    "TUN": "XNF",
    "TUR": "TUR",
    "TKM": "CIS",
    "TCA": "XLM",
    "TUV": "XSA",
    "UGA": "XAF",
    "UKR": "CIS",
    "ARE": "XME",
    "GBR": "XE25",
    "USA": "USA",
    "URY": "XLM",
    "UZB": "CIS",
    "VUT": "XSA",
    "VEN": "XLM",
    "VNM": "XSE",
    "VIR": "XLM",
    "PSE": "XME",
    "YEM": "XME",
    "ZMB": "XAF",
    "ZWE": "XAF"
}


df["region_agg"] = df["country3"].map(mapping)

df_agg = df.groupby(
    ["year", "region_agg", "type"], 
    as_index=False
)["value"].sum()

# ---------- 5. 最终整理成你想要的格式 ----------
df_result = df_agg[[ "region_agg", "year", "type", "value"]].copy()

# ---------- 6. 保存 ----------
df_result.to_csv("./CSV/basin aggregated.csv", index=False)

print("完成！结果保存")
